before_script:
  - $COMMIT_TIME=$(git show -s --format=%cd $CI_COMMIT_SHA --date=short)

variables: 
  branch: "master"
  tag_nmae: "build-master"

stages:
  - build
  - deploy
  
build:
  stage: build
  script:
    - export DLC=/usr/dlc117
    - cd myproject/target/oe/
    - rm -rf *
    - pwd
    - cd ../../../
    - git fetch https://${GIT_USER}:${GIT_PASS}@git.javra.com/proponent/proquote.git $branch
    - git reset --hard HEAD
    - git checkout $branch
    - git reset --hard HEAD
    - git clean -fd
    - git pull https://${GIT_USER}:${GIT_PASS}@git.javra.com/proponent/proquote.git $branch
    - ant build
    - cd myproject/Javascript
    - npm run build
    - mv myproject/target/oe/* myproject
    - cd ..
    - git add .
    - git commit -m '[ci skip]Build'
    - git push https://${GIT_USER}:${GIT_PASS}@gitlab.com/mzitx/cicd.git $branch
    # $GIT_USER & ${GIT_PASS} are the variables for git credentials defined in the settings/variables section. Please write your own variables
    - git tag -a build-$CI_PIPELINE_ID -m "[skip ci]"
    # $CI_PIPELINE_ID in built variable for each pipeline id
    - git push https://$GIT_USER:$GIT_PASS@gitlab.com/mzitx/cicd.git build-$CI_PIPELINE_ID 
    - echo 'Build finished and tagged!'
    
  when: manual
  only: 
    - master


deploy:
  stage: deploy
  script:
    - sshpass -p $SSH_PASS_SERVER ssh -t -t -o StrictHostKeyChecking=no -o RequestTTY=yes root@$SSH_IP_SERVER "cd /home/user/cicd/ && sudo git checkout . && sudo git fetch https://$GIT_USER:$GIT_PASS@gitlab.com/mzitx/cicd.git tag build-${CI_PIPELINE_ID} && git clean -fd && git reset -hard head && git status && sudo git checkout build-${CI_PIPELINE_ID}" 
    # $SSH_PASS_SERVER -> Password for the ssh address
    # @$SSH_IP_SERVER -> IP of the server 
    - echo 'Deployed!'
  
  when: manual
  only: 
    - master


