stages:
  - build
  - deploy
  
build:
  stage: build
  script:
    - pwd
    - export DLC=/usr/dlc117
    - echo $DLC
    - cd myproject/target/oe/
    - rm -rf *
    - pwd
    - cd ../../../
    - git fetch origin test
    - git checkout test
    - git checkout master
    - git branch -D test
    - git fetch origin test
    - git checkout test
    - ant build
    - mv myproject/target/oe/* myproject
    - git add .
    - git commit -m '[ci skip]Build'
    - git push https://${GIT_USER}:${GIT_PASS}@gitlab.com/mzitx/cicd.git test
    # $GIT_USER & ${GIT_PASS} are the variables for git credentials defined in the settings/variables section. Please write your own variables
    - git tag -a build-$CI_PIPELINE_ID -m "[skip ci]"
    # $CI_PIPELINE_ID in built variable for each pipeline id
    - git push https://$GIT_USER:$GIT_PASS@gitlab.com/mzitx/cicd.git build-$CI_PIPELINE_ID 
    - echo 'Build finished and tagged!'

deploy:
  stage: deploy
  script:
    - sshpass -p $SSH_PASS_SERVER ssh -t -t -o StrictHostKeyChecking=no -o RequestTTY=yes root@$SSH_IP_SERVER "cd /home/user/cicd/ && sudo git checkout . && sudo git fetch https://$GIT_USER:$GIT_PASS@gitlab.com/mzitx/cicd.git tag build-${CI_PIPELINE_ID} && git status && sudo git checkout build-${CI_PIPELINE_ID}" 
    # $SSH_PASS_JAVRA -> Password for the ssh address
    # @$SSH_IP_JAVRA -> IP of the server 
    - echo 'Deployed!'
  when: manual

